# .gitpod.yml

# Configuración de los puertos y servicios
ports:
  - port: 3000 # Puerto para el frontend React (Vite)
    onOpen: open-browser # Abrir automáticamente en el navegador
  - port: 8000 # Puerto para el servidor de desarrollo PHP
    onOpen: ignore # No abrir automáticamente, lo usaremos como API

# Tareas que se ejecutarán automáticamente al iniciar el espacio de trabajo
tasks:
  - name: Start PHP Backend
    init: |
      # Instalar PHP si no está disponible (Gitpod suele tenerlo)
      # Si necesitas extensiones PHP específicas, las instalarías aquí
      echo "Starting PHP development server..."
    command: |
      # Navega a la carpeta de tu API PHP
      cd backend/api
      # Inicia el servidor de desarrollo de PHP en el puerto 8000
      # --docroot=. asegura que el servidor sirva archivos desde la carpeta actual
      php -S 0.0.0.0:8000
    # Ejecutar en un terminal separado
    openMode: split-right

  - name: Install Frontend Dependencies & Start React App
    init: |
      echo "Installing frontend dependencies..."
      cd frontend
      npm install
    command: |
      echo "Starting React development server..."
      cd frontend
      npm run dev
    # Ejecutar en un terminal separado
    openMode: split-panel


